"""Generates the synthetic option-chain fixtures used by fixture-mode
ingestion, the unit tests, and the backtester in this environment (no live
NSE access this session -- see docs/WHITEPAPER.md rollout notes).

Output JSON matches `nsepython.nse_optionchain_scrapper`'s real schema
exactly (see core/nse_python_adapter.py's module docstring), so
`NSEPythonAdapter(use_fixture=True)` parses these identically to a live
payload. Prices are generated by pricing a synthetic-but-realistic index
skew through this project's own Black-Scholes engine
(core/pricer_bindings.py) -- NOT recorded from any real market -- so the
whole pipeline (ingestion -> SVI fit -> quoting -> backtest) sees internally
consistent, arbitrage-free-ish quotes rather than hand-typed numbers.

Re-run with `python -m data.sample_data.generate_fixtures` to regenerate
(deterministic given the fixed RNG seed).
"""

from __future__ import annotations

import json
import math
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np  # noqa: E402

from core.pricer_bindings import price as bs_price  # noqa: E402

RNG = np.random.default_rng(seed=42)

VALUATION_DT = datetime(2026, 8, 27, 15, 30, 0)
R = 0.065
Q = 0.065


def _skewed_iv(k: float, base_iv: float, skew: float, convexity: float) -> float:
    """Simple parametric index skew (higher IV for OTM puts, i.e. negative
    k, than OTM calls) -- just enough curvature for a realistic-looking
    smile that SVI can then fit; not derived from any real market print.
    """
    return max(base_iv + skew * k + convexity * k * k, 0.03)


STRIKE_STEP_MULTIPLIERS = (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5)
"""Real NSE chains widen strike spacing as you move away from the ATM
cluster (dense near the money, sparser far OTM). Cumulative sum of these
multipliers gives strike offsets in units of `strike_step` on each side of
ATM, producing a realistically wide moneyness range (needed for the SVI
curvature params to be well identified -- a narrow strike band makes b/rho/m
numerically degenerate)."""


def _strike_offsets(strike_step: float) -> list[float]:
    offsets = [0.0]
    cum = 0
    for mult in STRIKE_STEP_MULTIPLIERS:
        cum += mult
        offsets.append(cum * strike_step)
    return sorted({*offsets, *[-o for o in offsets]})


def _expiry_dates(n_weekly: int = 2, n_monthly: int = 1) -> list[date]:
    d = VALUATION_DT.date()
    expiries = []
    for i in range(1, n_weekly + 1):
        expiries.append(d + timedelta(days=7 * i))
    expiries.append(d + timedelta(days=35))
    return sorted(set(expiries))[: n_weekly + n_monthly]


def _build_chain(symbol: str, spot: float, strike_step: float, base_iv: float) -> dict:
    expiries = _expiry_dates()
    data_rows = []
    offsets = _strike_offsets(strike_step)

    for expiry in expiries:
        T = max((expiry - VALUATION_DT.date()).days, 1) / 365.0
        forward = spot * math.exp((R - Q) * T)
        atm_strike = round(spot / strike_step) * strike_step

        for offset in offsets:
            strike = atm_strike + offset
            if strike <= 0:
                continue
            k = math.log(strike / forward)
            iv = _skewed_iv(k, base_iv=base_iv, skew=-0.5, convexity=1.8)

            row = {"strikePrice": strike, "expiryDate": expiry.strftime("%d-%b-%Y")}
            for opt_key, is_call in (("CE", True), ("PE", False)):
                theo = bs_price(spot, strike, T, R, Q, iv, is_call)
                theo = max(theo, 0.05)
                half_spread = max(theo * 0.02, 0.05)
                bid = round(max(theo - half_spread, 0.0), 2)
                ask = round(theo + half_spread, 2)
                ltp = round(theo + RNG.normal(0, half_spread * 0.3), 2)

                # OI/volume peak near ATM and decay with |k|, plus noise --
                # gives the toxicity/feature-engineering layer something
                # non-trivial to compute over.
                decay = math.exp(-4.0 * k * k)
                oi = int(max(RNG.normal(150_000, 30_000), 500) * decay)
                volume = int(max(RNG.normal(40_000, 12_000), 100) * decay)
                change_oi = int(RNG.normal(0, oi * 0.08))

                row[opt_key] = {
                    "strikePrice": strike,
                    "expiryDate": expiry.strftime("%d-%b-%Y"),
                    "openInterest": oi,
                    "changeinOpenInterest": change_oi,
                    "totalTradedVolume": volume,
                    "impliedVolatility": round(iv * 100, 2),  # NSE reports IV in % units
                    "lastPrice": ltp,
                    "change": round(RNG.normal(0, half_spread), 2),
                    "bidQty": int(max(RNG.normal(300, 100), 0)) or 75,
                    "bidprice": bid,
                    "askPrice": ask,
                    "askQty": int(max(RNG.normal(300, 100), 0)) or 75,
                    "underlyingValue": spot,
                }
            data_rows.append(row)

    return {
        "records": {
            "expiryDates": [e.strftime("%d-%b-%Y") for e in expiries],
            "underlyingValue": spot,
            "timestamp": VALUATION_DT.strftime("%d-%b-%Y %H:%M:%S"),
            "data": data_rows,
        },
        "filtered": {},
    }


def main() -> None:
    out_dir = Path(__file__).parent
    fixtures = {
        "nifty_chain_sample.json": _build_chain("NIFTY", spot=25000.0, strike_step=50.0, base_iv=0.13),
        "banknifty_chain_sample.json": _build_chain("BANKNIFTY", spot=52000.0, strike_step=100.0, base_iv=0.16),
    }
    for filename, payload in fixtures.items():
        out_path = out_dir / filename
        out_path.write_text(json.dumps(payload, indent=2))
        n_rows = len(payload["records"]["data"])
        print(f"wrote {out_path} ({n_rows} strike rows, {len(payload['records']['expiryDates'])} expiries)")


if __name__ == "__main__":
    main()
